### ISSUE TITLE
Can't start meteor without a working mongo connection

### ISSUE THREAD

**Issue by mnmtanish** [meteorhacks/meteorx#4]
When meteorx is installed, the application will not start unless there's a working mongodb connection. Application crashes with error.

```
 Error: MONGO_URL must be set in environment
     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:1)
     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
     at new Mongo.Collection (packages/mongo/collection.js:98:1)
     at exposeMongoLivedata (packages/meteorhacks:meteorx/lib/mongo-livedata.js:3:1)
     at packages/meteorhacks:meteorx/lib/server.js:21:1
```

**Comment by patrickdreyer** [comment]
Same for me.
Does anybody have any clue or even a plan on how support MongoDB less applications?
