### ISSUE TITLE
Cannot run project after adding the package

### ISSUE THREAD

**Issue by anthonyboutinov** [meteorhacks/meteorx#6]
I'm running Meteor 1.2 and I get the following error message when I add this package to the project (add using 'meteor add' command, installs v. 1.0.2):

/Users/boutinov/.meteor/packages/meteor-tool/.1.1.8.tvnipv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: use "new" to construct a Mongo.Collection
    at [object Object].Mongo.Collection (packages/mongo/collection.js:29:1)
    at [object Object].ns.Collection (packages/matb33_collection-hooks/packages/matb33_collection-hooks.js:198:1)
    at exposeMongoLivedata (packages/meteorhacks_meteorx/packages/meteorhacks_meteorx.js:80:1)
    at Package (packages/meteorhacks_meteorx/packages/meteorhacks_meteorx.js:110:1)
    at Package (packages/meteorhacks_meteorx/packages/meteorhacks_meteorx.js:114:1)
    at /Users/boutinov/Sites/kink-meteor/.meteor/local/build/programs/server/packages/meteorhacks_meteorx.js:137:4
    at /Users/boutinov/Sites/kink-meteor/.meteor/local/build/programs/server/packages/meteorhacks_meteorx.js:146:3
    at /Users/boutinov/Sites/kink-meteor/.meteor/local/build/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/boutinov/.meteor/packages/meteor-tool/.1.1.8.tvnipv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
Exited with code: 8

**Comment by arunoda** [comment]
Just buy looking at the error message, it seems like you are trying to create collection, without invoking `new`.

Anyway, I'd like to see a sample repo with this error.

**Comment by anthonyboutinov** [comment]
It's happening inside exposeMongoLiveData inside packages/meteorhacks_meteorx/packages/meteorhacks_meteorx.js:80:1. So it's not my code, it's yours. And I don't know how can _I_ fix it other than reporting this issue to you.

**Comment by anthonyboutinov** [comment]
The error has disappeared with recent updates
