### ISSUE TITLE
TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by rpong** [meteorhacks/meteorx#8]
Since this change has been implemented: https://github.com/meteor/meteor/pull/10053

meteorhacks:meteorx is throwing the following error during build:

```
TypeError: Cannot read property 'constructor' of undefined
    at exposeSessionCollectionView (packages/meteorhacks_meteorx.js:73:62)
    at exposeLivedata (packages/meteorhacks_meteorx.js:32:5)
    at packages/meteorhacks_meteorx.js:176:1
    at packages/meteorhacks_meteorx.js:201:4
    at packages/meteorhacks_meteorx.js:209:3
    at /xxx/.meteor/local/build/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /xxx/.meteor/local/build/programs/server/boot.js:220:19
    at /xxx/.meteor/local/build/programs/server/boot.js:471:5
    at Function.run (/xxx/.meteor/local/build/programs/server/profile.js:510:12)
    at /xxx/.meteor/local/build/programs/server/boot.js:470:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

The fix is to change `session._namedSubs.[subId];` to `session._namedSubs.has(subId);` and `documentView.documents.[id].constructor;` to `documentView.documents.has(id).constructor;` in `/lib/livedata.js` for `exposeSubscription()` and `exposeSessionCollectionView()`

**Comment by lh0x00** [comment]
I fixed at https://github.com/meteorhacks/meteorx/pull/9
if you want use unblock publications, you can try [meteor unblock](https://github.com/lamhieu-vk/unblock) for new version.

**Comment by s7dhansh** [comment]
@arunoda can we kindly get this pr merged and create a new major version?
if not, @lamhieu-vk can you please publish a new package under your name, if you plan to keep contributing.

**Comment by macrozone** [comment]
unfortunatly this package here is unmaintained. We should get rid of it as a dependency.

**Comment by benjamn** [comment]
For those using `meteorhacks:meteorx` through `mdg:meteor-apm-agent`, we've just published version 3.2.0-rc.0 of `mdg:meteor-apm-agent` which no longer depends on `meteorhacks:meteorx` (though it does borrow some of its tricks, in a way that fixes this problem). To update, just put `mdg:meteor-apm-agent@3.2.0-rc.0` in the `.meteor/packages` file in your app(s). As soon as we have some confirmation that this version works, we'll release a final version without the `-rc.n` suffix.

**Comment by lh0x00** [comment]
@macrozone  @rpong @benjamn 
I have consulted the author and I decided to fork the project and maintain it in the future, it will be an open project for the community and for our company.

You can see details here:
https://github.com/lamhieu-vk/meteorx

**Comment by crapthings** [comment]
but no unblock support for new version?

**Comment by lh0x00** [comment]
@crapthings 
Unblock for Meteor Publications project will maintenance here: 
https://github.com/lamhieu-vk/unblock

**Comment by fumbleforce** [comment]
For those who are using other packages which have not yet been updated to use lamhieu's new fork, you can make a temporary "proxy" package for meteorhacks:meteorx by making a `meteorx` folder under `/packages`, with a `package.js` containing the content below. This will uninstall the meteorhacks version and install the lamhieu version instead! It worked for me, but of course as the packages that use the old version are not updated, they might not work 100% guaranteed.

```
Package.describe({
  name: "meteorhacks:meteorx",
  summary: "Proxy for getting another meteorx fork",
  version: "1.4.1"
});

Package.onUse((api) => {
  api.export("MeteorX");
  api.use([
    "lamhieu:meteorx",
  ]);
});
```

**Comment by lh0x00** [comment]
@jorgeer It's very nice!

**Comment by tab00** [comment]
Thanks for the workaround @jorgeer!

I was getting the error because https://github.com/nerdvibe/sikka-CM depends on meteorhacks:meteorx.
